CREATE TABLE `file_storage`.`users` 
( 
`ID` VARCHAR(36) NOT NULL , 
`FirstName` VARCHAR(100) NOT NULL , 
`LastName` VARCHAR(100) NOT NULL , 
`Email` VARCHAR(100) NOT NULL , 
`DisplayName` VARCHAR(100) NOT NULL , 
`UserName` VARCHAR(100) NOT NULL , 
`Password` VARCHAR(100) NOT NULL , 
`Created` DATE NOT NULL , 
PRIMARY KEY (`ID`(36))
) ENGINE = MyISAM; 